"""Command-line helpers for local laptop use.

Two subcommands sit alongside the default ``serve`` behaviour:

* ``mssql-mcp-server init`` — interactive wizard: asks 3-4 questions,
  auto-detects the ODBC driver, writes a starter ``.env``, and prints
  the Claude Desktop config block ready to paste.
* ``mssql-mcp-server doctor`` — preflight: probes Python, ODBC, settings,
  audit log, optionally an Entra token, and finally a real ``SELECT 1``.
  Each check reports PASS / WARN / FAIL with a one-line fix-it.

Both commands defer importing :mod:`mssql_mcp.server` so they work even
when the environment is incomplete."""

from __future__ import annotations

import argparse
import contextlib
import json
import platform
import re
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import IO, Any, Literal

from mssql_mcp import __version__

CheckStatus = Literal["PASS", "WARN", "FAIL", "INFO"]


# --- Shared helpers --------------------------------------------------------


_DRIVER_VERSION_RE = re.compile(r"ODBC Driver (\d+) for SQL Server")


def _driver_rank(name: str) -> tuple[int, int]:
    """Rank ODBC drivers so newer "ODBC Driver N" beats legacy "SQL Server"."""
    match = _DRIVER_VERSION_RE.match(name)
    if match:
        return (1, int(match.group(1)))
    return (0, 0)


def _detect_sql_drivers() -> list[str]:
    """Return ``pyodbc.drivers()`` filtered to SQL Server drivers, newest first."""
    try:
        import pyodbc
    except ImportError:  # pragma: no cover - pyodbc is a hard dep
        return []
    drivers = [d for d in pyodbc.drivers() if "SQL Server" in d]
    drivers.sort(key=_driver_rank, reverse=True)
    return drivers


def _is_windows() -> bool:
    return platform.system() == "Windows"


def _default_env_path() -> Path:
    return Path.cwd() / ".env"


# --- init ------------------------------------------------------------------


@dataclass
class _WizardAnswers:
    server: str
    port: int
    database: str
    auth_mode: str
    username: str | None = None
    password: str | None = None
    azure_tenant_id: str | None = None
    azure_client_id: str | None = None
    azure_client_secret: str | None = None
    driver: str = "ODBC Driver 18 for SQL Server"


def _prompt(
    stdin: IO[str],
    stdout: IO[str],
    question: str,
    default: str | None = None,
) -> str:
    suffix = f" [{default}]" if default else ""
    stdout.write(f"  {question}{suffix}: ")
    stdout.flush()
    raw = stdin.readline()
    # PowerShell's pipe injects a UTF-8 BOM at the start of stdin; strip it.
    answer = raw.lstrip("﻿").rstrip("\n").rstrip("\r").strip()
    if not answer and default is not None:
        return default
    return answer


def _prompt_choice(
    stdin: IO[str],
    stdout: IO[str],
    choices: Sequence[tuple[str, str]],
    default_index: int = 0,
) -> str:
    """Render ``choices`` as a numbered menu and return the chosen value."""
    for i, (_value, label) in enumerate(choices, start=1):
        marker = " (default)" if i - 1 == default_index else ""
        stdout.write(f"    {i}) {label}{marker}\n")
    while True:
        raw = _prompt(stdin, stdout, "Pick", str(default_index + 1))
        try:
            idx = int(raw) - 1
        except ValueError:
            stdout.write("    Please enter a number.\n")
            continue
        if 0 <= idx < len(choices):
            return choices[idx][0]
        stdout.write(f"    Pick between 1 and {len(choices)}.\n")


def _write_env(path: Path, answers: _WizardAnswers) -> None:
    lines = [
        "# Generated by `mssql-mcp-server init`",
        f"MSSQL_SERVER={answers.server}",
        f"MSSQL_PORT={answers.port}",
        f"MSSQL_DATABASE={answers.database}",
        f"MSSQL_DRIVER={answers.driver}",
        f"MSSQL_AUTH_MODE={answers.auth_mode}",
    ]
    if answers.auth_mode == "sql":
        lines += [
            f"MSSQL_USERNAME={answers.username or ''}",
            f"MSSQL_PASSWORD={answers.password or ''}",
        ]
    if answers.auth_mode == "entra_service_principal":
        lines += [
            f"AZURE_TENANT_ID={answers.azure_tenant_id or ''}",
            f"AZURE_CLIENT_ID={answers.azure_client_id or ''}",
            f"AZURE_CLIENT_SECRET={answers.azure_client_secret or ''}",
        ]
    lines += [
        "",
        "MSSQL_READ_ONLY=true",
        "MSSQL_ALLOW_DDL=false",
        "MSSQL_MAX_ROWS=1000",
        "MSSQL_QUERY_TIMEOUT=30",
        "",
        "MSSQL_AUDIT_LOG_PATH=./logs/audit.jsonl",
        "MCP_TRANSPORT=stdio",
        "LOG_LEVEL=INFO",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def _claude_desktop_snippet(answers: _WizardAnswers) -> str:
    env_block: dict[str, str] = {
        "MSSQL_SERVER": answers.server,
        "MSSQL_DATABASE": answers.database,
        "MSSQL_AUTH_MODE": answers.auth_mode,
        "MSSQL_READ_ONLY": "true",
    }
    if answers.auth_mode == "sql":
        env_block["MSSQL_USERNAME"] = answers.username or ""
        env_block["MSSQL_PASSWORD"] = answers.password or ""
    if answers.auth_mode == "entra_service_principal":
        env_block["AZURE_TENANT_ID"] = answers.azure_tenant_id or ""
        env_block["AZURE_CLIENT_ID"] = answers.azure_client_id or ""
        env_block["AZURE_CLIENT_SECRET"] = answers.azure_client_secret or ""
    snippet = {
        "mcpServers": {
            "mssql": {
                "command": "mssql-mcp-server",
                "env": env_block,
            }
        }
    }
    return json.dumps(snippet, indent=2)


def _run_wizard(
    stdin: IO[str], stdout: IO[str], env_path: Path
) -> _WizardAnswers:
    stdout.write("mssql-mcp-server setup wizard\n")
    stdout.write("=============================\n\n")

    if env_path.exists():
        stdout.write(f"An .env file already exists at {env_path}.\n")
        proceed = _prompt(
            stdin, stdout, "Overwrite? (y/N)", "N"
        ).strip().lower()
        if proceed not in ("y", "yes"):
            raise SystemExit("Aborted; .env unchanged.")
        stdout.write("\n")

    stdout.write("Where does your SQL Server live?\n")
    server = _prompt(stdin, stdout, "Server", "localhost")
    port_str = _prompt(stdin, stdout, "Port", "1433")
    try:
        port = int(port_str)
    except ValueError as exc:
        raise SystemExit(f"Port must be a number, got {port_str!r}") from exc
    database = _prompt(stdin, stdout, "Database")
    if not database:
        raise SystemExit("A database name is required.")

    stdout.write("\nHow should we authenticate?\n")
    auth_choices: list[tuple[str, str]] = []
    if _is_windows():
        auth_choices.append(
            ("windows", "Windows integrated auth (uses your Windows login)")
        )
    auth_choices += [
        ("sql", "SQL login (username + password)"),
        ("entra_cli", "Entra ID via Azure CLI (run 'az login' first)"),
        (
            "entra_service_principal",
            "Entra ID service principal (tenant + client + secret)",
        ),
        ("entra_default", "Entra ID auto-detect (DefaultAzureCredential)"),
    ]
    auth_mode = _prompt_choice(stdin, stdout, auth_choices, default_index=0)

    answers = _WizardAnswers(
        server=server, port=port, database=database, auth_mode=auth_mode
    )

    if auth_mode == "sql":
        stdout.write("\nSQL login\n")
        answers.username = _prompt(stdin, stdout, "Username")
        answers.password = _prompt(stdin, stdout, "Password")
    elif auth_mode == "entra_service_principal":
        stdout.write("\nService principal\n")
        answers.azure_tenant_id = _prompt(stdin, stdout, "Tenant ID")
        answers.azure_client_id = _prompt(stdin, stdout, "Client ID")
        answers.azure_client_secret = _prompt(stdin, stdout, "Client secret")

    drivers = _detect_sql_drivers()
    if drivers:
        stdout.write("\nDetected ODBC drivers:\n")
        for d in drivers:
            stdout.write(f"  - {d}\n")
        answers.driver = drivers[0]
        stdout.write(f"Using: {answers.driver}\n")
    else:
        stdout.write(
            "\nNo Microsoft ODBC SQL Server drivers detected. The .env "
            "will assume 'ODBC Driver 18 for SQL Server' — install it "
            "from learn.microsoft.com if you haven't already.\n"
        )

    return answers


def cmd_init(
    args: argparse.Namespace,
    *,
    stdin: IO[str] | None = None,
    stdout: IO[str] | None = None,
) -> int:
    """Run the interactive setup wizard. Returns a process exit code."""
    stdin_ = stdin or sys.stdin
    stdout_ = stdout or sys.stdout

    env_path = Path(args.env_path) if args.env_path else _default_env_path()
    try:
        answers = _run_wizard(stdin_, stdout_, env_path)
    except SystemExit as exc:
        msg = str(exc) if exc.code not in (None, 0) else ""
        if msg:
            stdout_.write(msg + "\n")
        return 1 if exc.code not in (None, 0) else 0

    _write_env(env_path, answers)
    stdout_.write(f"\nWrote {env_path}\n\n")

    stdout_.write(
        "To register with Claude Desktop, add this to your\n"
        "claude_desktop_config.json (path differs by OS):\n\n"
    )
    stdout_.write(_claude_desktop_snippet(answers))
    stdout_.write("\n\n")
    stdout_.write("Next: run `mssql-mcp-server doctor` to verify the setup.\n")
    return 0


# --- doctor ----------------------------------------------------------------


@dataclass
class _Check:
    name: str
    status: CheckStatus
    detail: str = ""
    fix: str = ""


def _check_python() -> _Check:
    major, minor = sys.version_info[:2]
    if (major, minor) >= (3, 11):
        return _Check(
            "Python version",
            "PASS",
            detail=f"{major}.{minor}.{sys.version_info[2]} (>= 3.11 required)",
        )
    return _Check(
        "Python version",
        "FAIL",
        detail=f"{major}.{minor} is too old",
        fix="Install Python 3.11 or newer",
    )


def _check_odbc_driver() -> _Check:
    drivers = _detect_sql_drivers()
    if not drivers:
        return _Check(
            "Microsoft ODBC SQL Server driver",
            "FAIL",
            detail="no SQL Server ODBC driver found",
            fix=(
                "Install the Microsoft ODBC Driver 18 for SQL Server: "
                "https://learn.microsoft.com/sql/connect/odbc/"
                "download-odbc-driver-for-sql-server"
            ),
        )
    return _Check(
        "Microsoft ODBC SQL Server driver",
        "PASS",
        detail=", ".join(drivers),
    )


def _check_settings() -> tuple[_Check, Any]:
    """Load Settings; return ``(check, settings_or_None)``."""
    try:
        from mssql_mcp.config import get_settings

        settings = get_settings()
    except Exception as exc:  # noqa: BLE001 - reported to user
        return (
            _Check(
                "Configuration",
                "FAIL",
                detail=str(exc).splitlines()[0],
                fix=(
                    "Run `mssql-mcp-server init`, or set MSSQL_SERVER / "
                    "MSSQL_DATABASE and any auth-mode-specific vars."
                ),
            ),
            None,
        )
    return (
        _Check(
            "Configuration",
            "PASS",
            detail=(
                f"auth_mode={settings.mssql_auth_mode}, "
                f"server={settings.mssql_server}, "
                f"database={settings.mssql_database}, "
                f"read_only={settings.mssql_read_only}"
            ),
        ),
        settings,
    )


def _check_audit_log(settings: Any) -> _Check:
    path = Path(settings.mssql_audit_log_path)
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        probe = path.parent / ".mssql_mcp_doctor_probe"
        probe.write_text("ok", encoding="utf-8")
        probe.unlink()
    except OSError as exc:
        return _Check(
            "Audit log writable",
            "FAIL",
            detail=str(exc),
            fix=f"Ensure {path.parent} is writable, or set MSSQL_AUDIT_LOG_PATH",
        )
    return _Check("Audit log writable", "PASS", detail=str(path))


def _check_token(settings: Any) -> _Check:
    if not settings.is_entra_auth:
        return _Check(
            "Entra token acquisition", "INFO", detail="not an Entra auth mode"
        )
    try:
        from mssql_mcp.auth import TokenProvider

        provider = TokenProvider(settings)
        token = provider.get_token()
    except Exception as exc:  # noqa: BLE001 - reported
        hint = ""
        if settings.mssql_auth_mode == "entra_cli":
            hint = "Run `az login` and try again."
        elif settings.mssql_auth_mode in (
            "entra_interactive",
            "entra_device_code",
        ):
            hint = "Complete the interactive sign-in prompt."
        return _Check(
            "Entra token acquisition",
            "FAIL",
            detail=str(exc).splitlines()[0],
            fix=hint or "Check your Entra credentials.",
        )
    return _Check(
        "Entra token acquisition",
        "PASS",
        detail=f"expires {token.expires_on.isoformat(timespec='seconds')}",
    )


def _check_connection(settings: Any) -> tuple[_Check, _Check | None]:
    """Open a connection and run ``SELECT 1``."""
    try:
        from mssql_mcp.db import Database
    except Exception as exc:  # noqa: BLE001
        return (
            _Check(
                "Database connection",
                "FAIL",
                detail=str(exc).splitlines()[0],
                fix="pyodbc import failed; reinstall the package.",
            ),
            None,
        )
    try:
        db = Database(settings)
        result = db.fetch("SELECT 1 AS ok")
    except Exception as exc:  # noqa: BLE001
        return (
            _Check(
                "Database connection",
                "FAIL",
                detail=str(exc).splitlines()[0][:200],
                fix=(
                    "Check that the server is reachable, the database "
                    "exists, and your principal has at least "
                    "db_datareader."
                ),
            ),
            None,
        )
    conn_check = _Check("Database connection", "PASS", detail="opened OK")
    if result.rows and list(result.rows[0].values())[0] == 1:
        select_check = _Check(
            "SELECT 1 round-trip",
            "PASS",
            detail=f"{result.duration_ms} ms",
        )
    else:
        select_check = _Check(
            "SELECT 1 round-trip", "WARN", detail="unexpected row"
        )
    return conn_check, select_check


def _format_status(status: CheckStatus) -> str:
    return {
        "PASS": "[ PASS ]",
        "WARN": "[ WARN ]",
        "FAIL": "[ FAIL ]",
        "INFO": "[ INFO ]",
    }[status]


def _emit_check(check: _Check, stdout: IO[str]) -> None:
    line = f"{_format_status(check.status)}  {check.name}"
    if check.detail:
        line += f" - {check.detail}"
    stdout.write(line + "\n")
    if check.status == "FAIL" and check.fix:
        stdout.write(f"           fix: {check.fix}\n")


def cmd_doctor(
    args: argparse.Namespace,
    *,
    stdout: IO[str] | None = None,
) -> int:
    """Probe the local install + connection. Returns 0 if all PASS/INFO."""
    out = stdout or sys.stdout
    out.write("mssql-mcp-server doctor\n")
    out.write("=======================\n\n")

    checks: list[_Check] = []
    fatal = False

    py_check = _check_python()
    _emit_check(py_check, out)
    checks.append(py_check)
    if py_check.status == "FAIL":
        fatal = True

    odbc_check = _check_odbc_driver()
    _emit_check(odbc_check, out)
    checks.append(odbc_check)
    if odbc_check.status == "FAIL":
        fatal = True

    settings_check, settings = _check_settings()
    _emit_check(settings_check, out)
    checks.append(settings_check)
    if settings is None:
        out.write("\nStopping early — see the configuration error above.\n")
        return 1

    audit_check = _check_audit_log(settings)
    _emit_check(audit_check, out)
    checks.append(audit_check)

    if not args.skip_token:
        token_check = _check_token(settings)
        _emit_check(token_check, out)
        checks.append(token_check)
        if token_check.status == "FAIL":
            fatal = True

    if not args.skip_db and not fatal:
        conn_check, select_check = _check_connection(settings)
        _emit_check(conn_check, out)
        checks.append(conn_check)
        if select_check is not None:
            _emit_check(select_check, out)
            checks.append(select_check)
        if conn_check.status == "FAIL":
            fatal = True
    elif args.skip_db:
        skip = _Check(
            "Database connection", "INFO", detail="skipped (--skip-db)"
        )
        _emit_check(skip, out)
        checks.append(skip)

    failures = sum(1 for c in checks if c.status == "FAIL")
    warnings = sum(1 for c in checks if c.status == "WARN")
    out.write("\n")
    if failures == 0 and warnings == 0:
        out.write("All checks passed.\n")
        return 0
    out.write(f"{failures} failure(s), {warnings} warning(s).\n")
    return 1 if failures > 0 else 0


# --- argparse entry --------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="mssql-mcp-server",
        description="MCP server for Microsoft SQL Server.",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"mssql-mcp-server {__version__}",
    )
    sub = parser.add_subparsers(dest="cmd")

    sub.add_parser(
        "serve",
        help=(
            "Run the MCP server on the configured transport "
            "(default when no subcommand is given)."
        ),
    )

    p_init = sub.add_parser("init", help="Interactive setup wizard")
    p_init.add_argument(
        "--env-path",
        default=None,
        help="Where to write the .env file (default: ./.env)",
    )

    p_doctor = sub.add_parser(
        "doctor", help="Diagnose configuration and connection"
    )
    p_doctor.add_argument(
        "--skip-token",
        action="store_true",
        help="Don't try to acquire an Entra token",
    )
    p_doctor.add_argument(
        "--skip-db",
        action="store_true",
        help="Don't open a real database connection",
    )
    return parser


def _reconfigure_stdio_utf8() -> None:
    """Force UTF-8 on stdin/stdout where the platform default is cp1252.

    Without this, PowerShell's `|` pipe injects the UTF-8 BOM as three
    cp1252 bytes (``Ã¯Â»Â¿``) instead of one U+FEFF char, and our BOM
    stripper can't match it."""
    for stream in (sys.stdin, sys.stdout):
        reconfigure = getattr(stream, "reconfigure", None)
        if callable(reconfigure):
            with contextlib.suppress(Exception):
                reconfigure(encoding="utf-8")


def dispatch(argv: Sequence[str] | None = None) -> int:
    _reconfigure_stdio_utf8()
    parser = build_parser()
    args = parser.parse_args(argv)
    cmd = args.cmd or "serve"
    if cmd == "init":
        return cmd_init(args)
    if cmd == "doctor":
        return cmd_doctor(args)
    # ``serve`` (or no subcommand)
    from mssql_mcp.server import mcp, settings

    if settings.mcp_transport == "stdio":
        mcp.run(transport="stdio")
    elif settings.mcp_transport == "http":
        mcp.run(transport="streamable-http")
    else:  # pragma: no cover - validated by pydantic Literal
        raise SystemExit(f"Unknown MCP_TRANSPORT: {settings.mcp_transport}")
    return 0
